
-- Run this in Supabase SQL Editor (project: funlove)

-- date_invite_config: holds the active invite name shown on the website
create table if not exists public.date_invite_config (
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- insert default name only if it doesn't already exist
insert into public.date_invite_config (name, active)
select 'Indu Reddy', true
where not exists (
  select 1 from public.date_invite_config where name = 'Indu Reddy'
);

alter table public.date_invite_config enable row level security;

create policy "Allow anonymous active invite name read"
on public.date_invite_config
for select
to anon
using (active = true);

-- date_responses: stores each anonymous response (no public read access)
create table if not exists public.date_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  invite_name text not null,
  date date not null,
  food text not null,
  restaurant text not null,
  area text not null
);

alter table public.date_responses enable row level security;

-- Allow anonymous inserts only (no anonymous select)
create policy "Allow anonymous inserts into date_responses"
on public.date_responses
for insert
to anon
with check (true);

create index if not exists date_responses_created_at_idx
on public.date_responses (created_at desc);
